const users = [
  {
    id: 1,
    bezeichnung: "Einführung in die Informatik",
    modulenr: "112(2)",
    code: "EINF",
    fachsemester: "1",
    studiengang: "Angewandte Informatik",
  },
  {
    id: 2,
    bezeichnung: "Hardware Konzepte",
    modulenr: "113",
    code: "HWK",
    fachsemester: "1",
    studiengang: "Angewandte Informatik",
  },
  {
    id: 3,
    bezeichnung: "Selbst- und Methodenkompetenz",
    modulenr: "111",
    code: "SMK",
    fachsemester: "1",
    studiengang: "Angewandte Informatik",
  },
  {
    id: 4,
    bezeichnung: "Diskrete Mathematik",
    modulenr: "115",
    code: "DMA",
    fachsemester: "1",
    studiengang: "Angewandte Informatik",
  },
  {
    id: 5,
    bezeichnung: "Betriebssysteme",
    modulenr: "114",
    code: "BS",
    fachsemester: "2",
    studiengang: "Angewandte Informatik",
  },
  {
    id: 6,
    bezeichnung: "Datenbanken",
    modulenr: "122",
    code: "DB",
    fachsemester: "2",
    studiengang: "Angewandte Informatik",
  },
  {
    id: 7,
    bezeichnung: "Rechnernetze und Netzwerksicherheit",
    modulenr: "123(2)",
    code: "BS",
    fachsemester: "2",
    studiengang: "Angewandte Informatik",
  },
  {
    id: 8,
    bezeichnung: "Objektorientierte Programmierung",
    modulenr: "124",
    code: "PROG2",
    fachsemester: "2",
    studiengang: "Angewandte Informatik",
  },
];

export default users;
